version: '3.4'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecom
    ports:
      - '5005:5005'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://$DB_USERNAME:$DB_PASSWORD@db:5432/$DB_NAME
    volumes:
      - ./src:/app/src

volumes:
  postgres_data:
